// Package public_api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package public_api

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// PostUser defines model for PostUser.
type PostUser struct {
	Firstname string  `json:"firstname"`
	Lastname  *string `json:"lastname,omitempty"`
	Password  string  `json:"password"`
	Username  string  `json:"username"`
}

// User defines model for User.
type User struct {
	Firstname string  `json:"firstname"`
	Lastname  *string `json:"lastname,omitempty"`
	Password  string  `json:"password"`
	Userid    string  `json:"userid"`
	Username  string  `json:"username"`
}

// DeleteUserParams defines parameters for DeleteUser.
type DeleteUserParams struct {
	// Username Username of the user to be deleted
	Username string `form:"username" json:"username"`
}

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	// Username Username to fetch the user information
	Username string `form:"username" json:"username"`
}

// PostUserJSONRequestBody defines body for PostUser for application/json ContentType.
type PostUserJSONRequestBody = PostUser

// PutUserFormdataRequestBody defines body for PutUser for application/x-www-form-urlencoded ContentType.
type PutUserFormdataRequestBody = User
