// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package idm

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type IdmUser struct {
	Uuid           uuid.UUID
	Username       string
	Password       []byte
	FirstName      string
	LastName       sql.NullString
	CreatedAt      time.Time
	LastModifiedAt time.Time
	DeletedAt      sql.NullTime
}

type IdmUserEmail struct {
	Uuid      uuid.UUID
	Email     string
	UserUuid  uuid.UUID
	CreatedAt time.Time
	DeletedAt sql.NullTime
}
